### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by PratishShrivastava** [Zubair-droid/hacktoberfest2021#10]
I would like to Update Readme.md please assign it to me. @Zubair-droid

**Comment by Zubair-droid** [comment]
Done 🤞. Go ahead.

> I would like to Update Readme.md please assign it to me. @Zubair-droid

**Comment by PratishShrivastava** [comment]
@Zubair-droid please add tags for hacktoberfest.

**Comment by PratishShrivastava** [comment]
why i am removed in this issue @Zubair-droid please add me again

**Comment by Zubair-droid** [comment]
> why i am removed in this issue @Zubair-droid please add me again

My bad. 
Done 🤞. Go ahead.

**Comment by Zubair-droid** [comment]
> why i am removed in this issue @Zubair-droid please add me again

Added 🤞. Go ahead.

**Comment by PratishShrivastava** [comment]
@Zubair-droid,  Kindly check this out and merge it

**Comment by Zubair-droid** [comment]
> @Zubair-droid, Kindly check this out and merge it

Great job dude 🤞😊. Liked the Readme.md

**Comment by PratishShrivastava** [comment]
hey @Zubair-droid can you mark label this issue as 'hacktoberfest-accepted' it would be very helpful.
