### ISSUE TITLE
Contribute placement coding questions

### ISSUE THREAD

**Issue by Zubair-droid** [Zubair-droid/hacktoberfest2021#2]
#hacktoberfestparticipating

**Comment by Raj-Thombare** [comment]
hey i am working on this please assign this to me!

**Comment by Zubair-droid** [comment]
> hey i am working on this please assign this to me!
>Done. Go ahead

**Comment by Zubair-droid** [comment]
@Raj-Thombare 
Done 🤞. Go ahead.

**Comment by Raj-Thombare** [comment]
Thanks, can i use any language??

**Comment by moh003-suh** [comment]
I can contribute merge sort, linear search and binary search in C language assign me these !!

**Comment by Zubair-droid** [comment]
> I can contribute merge sort, linear search and binary search in C language assign me these !!

Done 🤞. Go ahead.

**Comment by nayan1xyz** [comment]
I would like to contribute "Merge two sorted Arrays without extra space".pls assign it to me @Zubair-droid .

**Comment by Zubair-droid** [comment]
Done 🤞. Go ahead.

> I would like to contribute "Merge two sorted Arrays without extra space".pls assign it to me @Zubair-droid .

**Comment by vedic-kalra** [comment]
hey i can add a few important questions using bitwise operators.can you please assign this to me
Regards

**Comment by Zubair-droid** [comment]
> hey i can add a few important questions using bitwise operators.can you please assign this to me Regards

Done 🤞. Go ahead.

**Comment by Sunil2407** [comment]
I can contribute....if u want!

**Comment by keerthi259** [comment]
Assign me

**Comment by Jayasrisonal** [comment]
Assign me

**Comment by Zubair-droid** [comment]
> Assign me

Done 🤞. Go ahead.

**Comment by Zubair-droid** [comment]
> Assign me

Done 🤞. Go ahead.

**Comment by monarchsharma** [comment]
I can solve array gfg questions. Assign me please

**Comment by Zubair-droid** [comment]
> I can contribute....if u want!

Done 🤞. Go ahead.

**Comment by Zubair-droid** [comment]
> I can solve array gfg questions. Assign me please

Done 🤞. Go ahead.

**Comment by vedic-kalra** [comment]
HEY, can I add a few more questions? please assign me again.
Thank You

**Comment by monarchsharma** [comment]
May I add another question? Please assign me again

**Comment by nayan1xyz** [comment]
I would like to contribute to "Kadane’s Algorithm," asked by various FAANG interviews. pls, assign it to me @Zubair-droid

**Comment by Zubair-droid** [comment]
@nayan1xyz @monarchsharma @vedic-kalra 
Done 🤞. Go ahead.

**Comment by guruakaashjn** [comment]
Hi I would like to contribute "Tower of Hanoi", "Move all zeroes to the end".
Please assign me the task.

**Comment by Zubair-droid** [comment]
> Hi I would like to contribute "Tower of Hanoi", "Move all zeroes to the end". Please assign me the task.

@guru24102001 Done 🤞. Go ahead.
